- qml/WiFiPage.qml
Signed-off-by: Simon Busch <morphis@gravedo.de>
> Enable WAN connectivity within WiFi configuration step

- qml/BasePage.qml
- qml/CountryPage.qml
- qml/NetworkIdCountryMapper.qml
- qml/TimeZonePage.qml
- qml/WiFiPage.qml
- qml/js/GlobalState.js
- qml/main.qml
> Country + timezone selection based on MCC

- qml/CountryPage.qml
- qml/LocalePage.qml
- qml/NetworkIdCountryMapper.qml
- qml/TimeZonePage.qml
- qml/js/GlobalState.js
Should work a bit faster now :)
> Improve mcc code for country + timezone a bit

- qml/NetworkConnectPage.qml
Signed-off-by: Simon Busch <morphis@gravedo.de>
> Add checkbox to show network passphrase

- qml/BasePage.qml
- qml/TimeZonePage.qml
Signed-off-by: Christophe Chapuis <chris.chapuis@gmail.com>
> Don"t show the Back button until the page is ready

- qml/TimeZonePage.qml
Made it Units.gu(4) as with the WiFi connect page, so it's better readable and consistent
> Add a height for the Textfield

- qml/FinishedPage.qml
This should be a workaround to solve at least
http://issues.webos-ports.org/issues/865 for now. Might need to be
revisited in the future.
> Add a reboot after First Use to work around missing activities

- qml/FeedsPage.qml
So it works in both orientations on Mako, Maguro and Tenderloin
> Tweak the layout for popup a bit

- qml/NetworkConnectPage.qml
- qml/WiFiPage.qml
Add support for Enterprise WiFi so you can enter username & password
> Initial support for Enterprise WiFi

- qml/main.qml
> Show WiFiPage only on device with WiFi

- qml/WiFiPage.qml
> Fix connecting to open networks from FirstUse

- qml/CountryPage.qml
- qml/FeedsPage.qml
- qml/LocalePage.qml
- qml/TimeZonePage.qml
Signed-off-by: Herman van Hazendonk github.com@herrie.org
> Code cleanup, layout tweaking & timeFormat selection

- licenses/main_en.html
- qml/BasePage.qml
- qml/CountryPage.qml
- qml/FeedsPage.qml
- qml/FinishedPage.qml
- qml/LicenseAgreementPage.qml
- qml/LocalePage.qml
- qml/TimeZonePage.qml
- qml/WebsiteDisplayPage.qml
- qml/WiFiPage.qml
- qml/main.qml
- test/imports/firstuse/main_en.html
* Fix AppMenu label (it should be "First Use")
* TimeZone page: show correct time in list, fix list height
* BasePage: wait for pages to activate to avoid bug when quickly tap on
*     bottom buttons
* Fix typo in license page
* Open links in final page in browser
* Save pages states while going between them
* Fix keyboard non closing on outside tap
* Use more contrast link color (red)
* Show load progress in browser
* WiFi page: Use subscribe call instead of timer
* Fix disappearing back buttons on page switch
* Fix switches in feeds page
* Correctly highlight items in filtered lists
Signed-off-by: Nikolay Nizov <nizovn@gmail.com>
> Various graphics improvements 2

- qml/FinishedPage.qml
- qml/LicenseAgreementPage.qml
Red is screaming too much. This still works on our background.
> Use #4db2ff as linkColor

- qml/FeedsPage.qml
Signed-off-by: Christophe Chapuis <chris.chapuis@gmail.com>
> FeedsPage: improve layout

- qml/FeedsPage.qml
User could still interact with background.
> FeedsPage: fix confirmation popup

- qml/WiFiPage.qml
Fixes warnings about forbidden anchors in a Layout
Signed-off-by: Christophe Chapuis <chris.chapuis@gmail.com>
> WiFiPage: fix attachements

- qml/FeedsPage.qml
To reflect changes in Preware package.
> FeedsPage.qml: Update ipkg service name

- appinfo.json
So we can make the appropriate calls from the FirstUse app.
> org.webosports.app.firstuse: Set requiredPermissions

- CMakeLists.txt
- plugin/CMakeLists.txt
- qml/main.qml
As per examples on:
https://doc-snapshots.qt.io/qt6-dev/cmake-qt5-and-qt6-compatibility.html
> CMakeLists.txt: Updated for Qt6
